import type { AvatarData } from "./avatar";

export const mockAvatars: AvatarData[] = [
  {
    id: "avatar-dev",
    name: "Claude",
    role: "dev",
    provider: "claude",
    color: "#bf00ff",
    modelUrl: "",
    status: "idle",
    currentAction: null,
    history: [],
    position: [-1.2, 0, 0.5],
    roomId: "room-dev",
    apiKey: "",
  },
  {
    id: "avatar-designer",
    name: "Gemini",
    role: "designer",
    provider: "gemini",
    color: "#ff003c",
    modelUrl: "",
    status: "idle",
    currentAction: null,
    history: [],
    position: [0.8, 0, 0.2],
    roomId: "room-dev",
    apiKey: "",
  },
  {
    id: "avatar-pm",
    name: "Mistral",
    role: "pm",
    provider: "mistral",
    color: "#ff2d7a",
    modelUrl: "",
    status: "idle",
    currentAction: null,
    history: [],
    position: [2.5, 0, -0.8],
    roomId: "room-dev",
    apiKey: "",
  },
];
